name: Build zkcloud
on:
  pull_request:
  merge_group:
  push:
    branches:
      - main
      - release/**
permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}-build
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-arch: ["amd64", "arm64"] # drop 32 bit support for now (and maybe forever)
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.24"
          check-latest: true
        ###################
        #### Build App ####
        ###################
      - name: Build
        run: GOARCH=${{ matrix.go-arch }} make build

