name: Tests / Code Coverage
on:
  pull_request:
  merge_group:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.24"
          check-latest: true
          cache: true
          cache-dependency-path: go.sum
      - name: test 
        run: |
            make test
